# Pull base image
FROM python:3.11

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /feed/

# Install dependencies
COPY requirements.txt /feed/
RUN pip install -r requirements.txt

COPY . /feed/
COPY .env_prod /feed/.env

EXPOSE 8000